CREATE DATABASE sigm_bd;

use sigm_bd;

CREATE TABLE employees(
    id INT NOT NULL AUTO_INCREMENT,
    names VARCHAR(50) NOT NULL,
    surnames VARCHAR(100) NOT NULL,
    rol VARCHAR(50) NOT NULL,
    phone VARCHAR(9) NOT NULL,
    status VARCHAR(1) NOT NULL,
    registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualization_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE spare_parts(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    stock VARCHAR(100) NOT NULL,
    type VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,
    registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualization_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE tools(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    status VARCHAR(1) NOT NULL,
    type VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,
    registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualization_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE tickets(
    id INT NOT NULL AUTO_INCREMENT,
    description TEXT NOT NULL,
    status VARCHAR(1) NOT NULL,
    registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualization_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE spare_parts_tickets(
    id INT NOT NULL AUTO_INCREMENT,
    id_spare_part INT NOT NULL,
    id_ticket INT NOT NULL,
    registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualization_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (id_spare_part) REFERENCES spare_parts(id),
    FOREIGN KEY (id_ticket) REFERENCES tickets(id)
);

CREATE TABLE tools_tickets(
    id INT NOT NULL AUTO_INCREMENT,
    id_tool INT NOT NULL,
    id_ticket INT NOT NULL,
    registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualization_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (id_tool) REFERENCES tools(id),
    FOREIGN KEY (id_ticket) REFERENCES tickets(id)
);

CREATE TABLE employees_tickets(
    id INT NOT NULL AUTO_INCREMENT,
    id_employee INT NOT NULL,
    id_ticket INT NOT NULL,
    registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualization_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (id_employee) REFERENCES employees(id),
    FOREIGN KEY (id_ticket) REFERENCES tickets(id)
);
